#ELIMINACION GAUSSIANA
#HERNANDEZ RUBIO DAIRA SAYURI 
# PRIMER PARCIAL 




In [1]:
import numpy
a= int(input('Numero de renglones: '))  #Aqui pedimos al usario el numero de renglones y columnas  
b= int(input('Numero de columnas: '))    
matriz = numpy.zeros((a,b))     #es para llenar la matriz con ceros 
vector= numpy.zeros((b))        #alamcenar los valores del vector 
x=numpy.zeros((a))              #alamcenar los resultados despues del proceso de operacion 

print('Introduce la matriz de coeficientes y la solución vectorial')

for r in range(0,a):        #r= son los renglones
    for c in range(0,b):    #c = son las columnas 
        matriz[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"] "))   #escribir los numerosdentro de la matriz   
    vector[(r)]=(input('b['+str(r+1)+']: '))    
print(matriz)       #Imprimir la matriz que tenemos 

for k in range (0,a):       
    for r in range(k+1, a):
        factor=(matriz[r,k]/matriz[k,k])    #es la parte que cambia los reglones 
        vector[r]=vector[r]-(factor*vector[k])  #son las operaciones para obtener los 0 
        for c in range  (0, b):
            matriz[r,c]=matriz[r,c]-(factor*matriz[k,c])    # involucra a las columnas y es para la matriz de coeficientes 

#sustitución hacia atrás
x[a-1]=vector[a-1]/matriz[a-1,b-1]     #despeje de la ultima variable de la matriz 
print(x[b-1])   

for r in range(a-2,-1,-1):     
    suma=0  #Guardar los valores de la multiplicacion 
    for c in range (0, b):
        suma=suma+matriz[r,c]*x[c]      #despeje que hace para conecer el resultado de las incognitas 
    x[r]=(vector[r]-suma)/matriz[r,r]   #es variable que controla los renglones 


print('Resultado matriz')
print(matriz)
print('Resultado del vector')
print(vector)
print('RESULTADO FINAL : ')
print(x)




Numero de renglones: 3
Numero de columnas: 3
Introduce la matriz de coeficientes y la solución vectorial
Elemento a[1,1] 2
Elemento a[1,2] 4
Elemento a[1,3] 6
b[1]: 18
Elemento a[2,1] 4
Elemento a[2,2] 5
Elemento a[2,3] 6
b[2]: 24
Elemento a[3,1] 3
Elemento a[3,2] 1
Elemento a[3,3] -2
b[3]: 4
[[ 2.  4.  6.]
 [ 4.  5.  6.]
 [ 3.  1. -2.]]
3.0
Resultado matriz
[[ 2.  4.  6.]
 [ 0. -3. -6.]
 [ 0.  0. -1.]]
Resultado del vector
[ 18. -12.  -3.]
RESULTADO FINAL : 
[ 4. -2.  3.]
